//! Two codegen passes, both driven by the vendored `schema/` assets:
//!
//! 1. `protocol.schema.json` (660 JSON Schema definitions) -> Rust types via `typify`.
//!    Written to `$OUT_DIR/protocol_generated.rs`, included by `src/protocol.rs`.
//! 2. `methods.json` (per-method name/params-type/response-type metadata, derived
//!    from the same schema by `schema/build_combined_schema.py`) -> ergonomic
//!    per-method wrapper functions. Written to `$OUT_DIR/methods_generated.rs`,
//!    included by `src/client.rs`.
//!
//! Regenerating the schema assets (after bumping the installed `codex` CLI):
//! see `schema/build_combined_schema.py`'s module docstring and this crate's README.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde_json::Value;

fn main() {
    println!("cargo:rerun-if-changed=schema/protocol.schema.json");
    println!("cargo:rerun-if-changed=schema/methods.json");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_dir = Path::new(&out_dir);

    generate_protocol_types(out_dir);
    generate_method_wrappers(out_dir);
}

fn generate_protocol_types(out_dir: &Path) {
    let content = fs::read_to_string("schema/protocol.schema.json")
        .expect("read schema/protocol.schema.json");
    let schema: schemars::schema::RootSchema = serde_json::from_str(&content)
        .expect("parse protocol.schema.json as a JSON Schema document");

    let settings = typify::TypeSpaceSettings::default();
    let mut type_space = typify::TypeSpace::new(&settings);
    type_space
        .add_root_schema(schema)
        .expect("typify: convert protocol.schema.json to Rust types");

    let tokens = type_space.to_stream();
    let file: syn::File = syn::parse2(tokens).expect("parse typify output as a Rust file");
    let formatted = prettyplease::unparse(&file);

    fs::write(out_dir.join("protocol_generated.rs"), formatted)
        .expect("write protocol_generated.rs");
}

struct MethodEntry {
    method: String,
    variant_name: String,
    fn_name: String,
    params_type: Option<String>,
    params_optional: bool,
    response_type: Option<String>,
}

fn parse_entries(value: &Value, with_response: bool) -> Vec<MethodEntry> {
    value
        .as_array()
        .expect("methods.json section is an array")
        .iter()
        .map(|e| MethodEntry {
            method: e["method"].as_str().unwrap().to_string(),
            variant_name: e["variant_name"].as_str().unwrap().to_string(),
            fn_name: e["fn_name"].as_str().unwrap().to_string(),
            params_type: e["params_type"].as_str().map(str::to_string),
            params_optional: e["params_optional"].as_bool().unwrap_or(false),
            response_type: if with_response {
                e["response_type"].as_str().map(str::to_string)
            } else {
                None
            },
        })
        .collect()
}

fn generate_method_wrappers(out_dir: &Path) {
    let content = fs::read_to_string("schema/methods.json").expect("read schema/methods.json");
    let manifest: Value = serde_json::from_str(&content).expect("parse methods.json");

    let client_requests = parse_entries(&manifest["client_requests"], true);
    let server_requests = parse_entries(&manifest["server_requests"], true);
    let server_notifications = parse_entries(&manifest["server_notifications"], false);

    let mut out = String::new();
    writeln!(
        out,
        "// GENERATED by build.rs from schema/methods.json - do not edit by hand."
    )
    .unwrap();

    // -------- ergonomic per-method wrappers on CodexAppServerClient --------
    writeln!(out, "impl CodexAppServerClient {{").unwrap();
    for e in &client_requests {
        let doc = format!("Calls the `{}` app-server method.", e.method);
        match (&e.params_type, e.params_optional, &e.response_type) {
            (Some(pt), false, Some(rt)) => {
                writeln!(
                    out,
                    r#"    #[doc = {doc:?}]
    pub async fn {fn_name}(&self, params: crate::protocol::{pt}) -> crate::Result<crate::protocol::{rt}> {{
        let value = self.call_request(|id| crate::protocol::ClientRequest::{variant} {{ id, params }}).await?;
        Ok(serde_json::from_value(value)?)
    }}"#,
                    doc = doc,
                    fn_name = e.fn_name,
                    pt = pt,
                    rt = rt,
                    variant = e.variant_name,
                )
                .unwrap();
            }
            (Some(pt), true, Some(rt)) => {
                writeln!(
                    out,
                    r#"    #[doc = {doc:?}]
    pub async fn {fn_name}(&self, params: Option<crate::protocol::{pt}>) -> crate::Result<crate::protocol::{rt}> {{
        let value = self.call_request(|id| crate::protocol::ClientRequest::{variant} {{ id, params }}).await?;
        Ok(serde_json::from_value(value)?)
    }}"#,
                    doc = doc,
                    fn_name = e.fn_name,
                    pt = pt,
                    rt = rt,
                    variant = e.variant_name,
                )
                .unwrap();
            }
            (None, _, Some(rt)) => {
                writeln!(
                    out,
                    r#"    #[doc = {doc:?}]
    pub async fn {fn_name}(&self) -> crate::Result<crate::protocol::{rt}> {{
        let value = self.call_request(|id| crate::protocol::ClientRequest::{variant} {{ id, params: () }}).await?;
        Ok(serde_json::from_value(value)?)
    }}"#,
                    doc = doc,
                    fn_name = e.fn_name,
                    rt = rt,
                    variant = e.variant_name,
                )
                .unwrap();
            }
            (Some(pt), false, None) => {
                // config/mcpServer/reload: has params but no response payload.
                writeln!(
                    out,
                    r#"    #[doc = {doc:?}]
    pub async fn {fn_name}(&self, params: crate::protocol::{pt}) -> crate::Result<()> {{
        self.call_request(|id| crate::protocol::ClientRequest::{variant} {{ id, params }}).await?;
        Ok(())
    }}"#,
                    doc = doc,
                    fn_name = e.fn_name,
                    pt = pt,
                    variant = e.variant_name,
                )
                .unwrap();
            }
            (Some(pt), true, None) => {
                writeln!(
                    out,
                    r#"    #[doc = {doc:?}]
    pub async fn {fn_name}(&self, params: Option<crate::protocol::{pt}>) -> crate::Result<()> {{
        self.call_request(|id| crate::protocol::ClientRequest::{variant} {{ id, params }}).await?;
        Ok(())
    }}"#,
                    doc = doc,
                    fn_name = e.fn_name,
                    pt = pt,
                    variant = e.variant_name,
                )
                .unwrap();
            }
            (None, _, None) => {
                writeln!(
                    out,
                    r#"    #[doc = {doc:?}]
    pub async fn {fn_name}(&self) -> crate::Result<()> {{
        self.call_request(|id| crate::protocol::ClientRequest::{variant} {{ id, params: () }}).await?;
        Ok(())
    }}"#,
                    doc = doc,
                    fn_name = e.fn_name,
                    variant = e.variant_name,
                )
                .unwrap();
            }
        }
    }
    writeln!(out, "}}").unwrap();

    // -------- typed server->client request enum + reply helpers --------
    writeln!(
        out,
        r#"
/// A server->client request the app-server sent us (approvals, elicitation, etc.),
/// paired with a one-shot reply channel. Obtain these from
/// [`EventStream::recv`](crate::EventStream::recv) as an [`Event::Request`](crate::Event::Request).
pub struct PendingServerRequest {{
    pub request: crate::protocol::ServerRequest,
    pub(crate) reply_tx: tokio::sync::oneshot::Sender<crate::transport::OutgoingReply>,
}}

impl std::fmt::Debug for PendingServerRequest {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        f.debug_struct("PendingServerRequest")
            .field("request", &self.request)
            .finish_non_exhaustive()
    }}
}}

impl PendingServerRequest {{
    /// The `RequestId` the app-server expects echoed back in the reply.
    pub fn id(&self) -> &crate::protocol::RequestId {{
        match &self.request {{"#
    )
    .unwrap();
    for e in &server_requests {
        writeln!(
            out,
            "            crate::protocol::ServerRequest::{variant} {{ id, .. }} => id,",
            variant = e.variant_name
        )
        .unwrap();
    }
    writeln!(
        out,
        r#"        }}
    }}

    /// Send a successful reply. `result` must serialize to the response shape
    /// the app-server expects for this specific method (see the matching
    /// `*Response` type for the method named by [`Self::method_name`]).
    pub fn respond(self, result: impl serde::Serialize) -> crate::Result<()> {{
        let id = self.id().clone();
        let value = serde_json::to_value(result)?;
        let _ = self.reply_tx.send(crate::transport::OutgoingReply::Result {{ id, result: value }});
        Ok(())
    }}

    /// Send an error reply.
    pub fn respond_error(self, code: i64, message: impl Into<String>, data: Option<serde_json::Value>) {{
        let id = self.id().clone();
        let _ = self.reply_tx.send(crate::transport::OutgoingReply::Error {{
            id,
            code,
            message: message.into(),
            data,
        }});
    }}

    /// The wire method name, e.g. `"execCommandApproval"`.
    pub fn method_name(&self) -> &'static str {{
        match &self.request {{"#
    )
    .unwrap();
    for e in &server_requests {
        writeln!(
            out,
            "            crate::protocol::ServerRequest::{variant} {{ .. }} => {method:?},",
            variant = e.variant_name,
            method = e.method,
        )
        .unwrap();
    }
    writeln!(out, "        }}\n    }}\n}}").unwrap();

    // -------- doc comment listing every notification variant handled by ServerNotification --------
    let notif_names: Vec<&str> = server_notifications
        .iter()
        .map(|e| e.method.as_str())
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect();
    writeln!(
        out,
        "\n/// All {n} server notification methods this crate can decode: {list:?}",
        n = notif_names.len(),
        list = notif_names,
    )
    .unwrap();
    writeln!(
        out,
        "pub const SERVER_NOTIFICATION_METHODS: &[&str] = &{notif:?};",
        notif = notif_names
    )
    .unwrap();

    fs::write(out_dir.join("methods_generated.rs"), out).expect("write methods_generated.rs");
}
