use anyhow::Result;
use serde_json::Value;

pub(super) fn render_provider_docs(snapshot: &Value) -> Result<String> {
    let mut out = String::from("# Generated Provider Surfaces\n\n");
    out.push_str("Generated by `cargo xtask generate-provider-surfaces`. Do not edit by hand.\n\n");
    out.push_str(&format!(
        "- Provider fingerprint: `{}`\n",
        snapshot["provider_fingerprint"].as_str().unwrap_or("")
    ));
    out.push_str("- Palette surface: deferred until the Axon tauri-palette port lands.\n\n");
    out.push_str("## Providers\n\n");
    for provider in snapshot["providers"].as_array().into_iter().flatten() {
        out.push_str(&format!(
            "### `{}` ({})\n\n",
            provider["name"].as_str().unwrap_or("unknown"),
            provider["kind"].as_str().unwrap_or("unknown")
        ));
        if let Some(description) = provider["description"].as_str() {
            out.push_str(description);
            out.push_str("\n\n");
        }
        out.push_str("| tool | MCP | CLI | REST | purpose |\n|---|---:|---:|---:|---|\n");
        for tool in provider["tools"].as_array().into_iter().flatten() {
            out.push_str(&format!(
                "| `{}` | {} | {} | {} | {} |\n",
                tool["name"].as_str().unwrap_or(""),
                yes_no(tool["mcp"].as_bool().unwrap_or(false)),
                yes_no(tool["cli"].as_bool().unwrap_or(false)),
                yes_no(tool["rest"].as_bool().unwrap_or(false)),
                tool["description"]
                    .as_str()
                    .unwrap_or("")
                    .replace('|', "\\|"),
            ));
        }
        out.push('\n');
    }
    Ok(out)
}

pub(super) fn render_provider_skill(provider: &Value) -> Result<String> {
    let name = provider["name"].as_str().unwrap_or("provider");
    let description = provider["description"]
        .as_str()
        .unwrap_or("Generated provider skill.");
    let action_names = provider["tools"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|tool| tool["name"].as_str())
        .take(4)
        .collect::<Vec<_>>()
        .join(", ");
    let when_to_use = provider["when_to_use"]
        .as_str()
        .filter(|value| !value.trim().is_empty())
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| {
            if action_names.is_empty() {
                format!("Use when working with the `{name}` provider.")
            } else {
                format!("Use when working with `{name}` provider actions such as {action_names}.")
            }
        });
    let mut out = format!(
        "---\nname: {name}\ndescription: {}\n---\n\nGenerated by `cargo xtask generate-provider-surfaces` from the current provider catalog.\n\n# `{name}` Provider\n\n{description}\n\n## When To Use\n\n{when_to_use}\n\n## Surface Selection\n\n",
        yaml_string(&when_to_use),
    );
    out.push_str(
        "- Use MCP first when the server is connected, especially for MCP-only actions.\n",
    );
    out.push_str("- Use CLI only when the action's CLI surface is `yes`; do not invent commands for `N/A` entries.\n");
    out.push_str("- Use REST only when the action's REST surface is `yes`; send JSON bodies matching the action schema.\n");
    out.push_str("- MCP-only elicitation actions require an elicitation-capable MCP client; do not attempt CLI or REST fallbacks.\n\n");
    out.push_str("## Tools\n\n");
    out.push_str("| tool | MCP | CLI | REST | CLI command | REST route | purpose |\n");
    out.push_str("|---|---:|---:|---:|---|---|---|\n");
    for tool in provider["tools"].as_array().into_iter().flatten() {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | `{}` | `{}` | {} |\n",
            tool["name"].as_str().unwrap_or(""),
            yes_no(tool["mcp"].as_bool().unwrap_or(false)),
            yes_no(tool["cli"].as_bool().unwrap_or(false)),
            yes_no(tool["rest"].as_bool().unwrap_or(false)),
            tool["cli_command"].as_str().unwrap_or(""),
            tool["rest_route"].as_str().unwrap_or(""),
            tool["description"]
                .as_str()
                .unwrap_or("")
                .replace('|', "\\|"),
        ));
    }
    out.push_str("\n## Action Reference\n\n");
    for tool in provider["tools"].as_array().into_iter().flatten() {
        render_tool_reference(&mut out, tool);
    }
    render_primitive_section(&mut out, "Prompts", &provider["prompts"]);
    render_primitive_section(&mut out, "Resources", &provider["resources"]);
    render_primitive_section(&mut out, "Tasks", &provider["tasks"]);
    render_primitive_section(&mut out, "Elicitation", &provider["elicitation"]);
    Ok(out)
}

fn render_tool_reference(out: &mut String, tool: &Value) {
    let name = tool["name"].as_str().unwrap_or("");
    out.push_str(&format!("### `{name}`\n\n"));
    out.push_str(tool["description"].as_str().unwrap_or(""));
    out.push_str("\n\n");
    out.push_str(&format!(
        "- Scope: `{}`\n",
        tool["scope"].as_str().unwrap_or("public/default")
    ));
    out.push_str(&format!(
        "- Cost: `{}`\n",
        tool["cost"].as_str().unwrap_or("unspecified")
    ));
    out.push_str(&format!(
        "- Destructive: `{}`\n",
        tool["destructive"].as_bool().unwrap_or(false)
    ));
    out.push_str(&format!(
        "- Requires admin: `{}`\n",
        tool["requires_admin"].as_bool().unwrap_or(false)
    ));
    out.push_str(&format!(
        "- Required args: `{}`\n",
        schema_required_args(&tool["input_schema"])
    ));
    out.push_str(&format!(
        "- Optional args: `{}`\n",
        schema_optional_args(&tool["input_schema"])
    ));
    out.push_str(&format!("- Output: `{}`\n", output_summary(tool)));
    out.push_str(&format!("- MCP: `example(action=\"{name}\")`\n"));
    if tool["cli"].as_bool().unwrap_or(false) {
        out.push_str(&format!(
            "- CLI: `rtemplate {}`\n",
            cli_usage(tool)
                .unwrap_or_else(|| tool["cli_command"].as_str().unwrap_or(name).to_owned())
        ));
        if let Some(flags) = cli_flags_summary(tool) {
            out.push_str(&format!("- CLI flags: {flags}\n"));
        }
        if let Some(aliases) = tool["cli_aliases"].as_array() {
            let aliases = aliases
                .iter()
                .filter_map(Value::as_str)
                .collect::<Vec<_>>()
                .join(", ");
            if !aliases.is_empty() {
                out.push_str(&format!("- CLI aliases: `{aliases}`\n"));
            }
        }
    } else {
        out.push_str("- CLI: `N/A` - do not call this action from CLI.\n");
    }
    if tool["rest"].as_bool().unwrap_or(false) {
        out.push_str(&format!(
            "- REST: `{}`\n",
            tool["rest_route"].as_str().unwrap_or("")
        ));
    } else {
        out.push_str("- REST: `N/A` - do not invent an HTTP route.\n");
    }
    if let Some(env) = env_summary(tool) {
        out.push_str(&format!("- Env: {env}\n"));
    }
    if let Some(examples) = examples_summary(tool) {
        out.push_str(&format!("- Examples: {examples}\n"));
    }
    if let Some(fallback) = scaffold_fallback_summary(tool) {
        out.push_str(&fallback);
    }
    out.push('\n');
}

fn yaml_string(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".to_owned())
}

fn schema_required_args(schema: &Value) -> String {
    let Some(required) = schema["required"].as_array() else {
        return "none".to_owned();
    };
    let args = required
        .iter()
        .filter_map(Value::as_str)
        .map(|name| format!("{name}: {}", schema_property_type(schema, name)))
        .collect::<Vec<_>>();
    if args.is_empty() {
        "none".to_owned()
    } else {
        args.join(", ")
    }
}

fn schema_optional_args(schema: &Value) -> String {
    let required = schema["required"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<std::collections::BTreeSet<_>>();
    let Some(properties) = schema["properties"].as_object() else {
        return "none".to_owned();
    };
    let args = properties
        .keys()
        .filter(|name| !required.contains(name.as_str()))
        .map(|name| format!("{name}: {}", schema_property_type(schema, name)))
        .collect::<Vec<_>>();
    if args.is_empty() {
        "none".to_owned()
    } else {
        args.join(", ")
    }
}

fn schema_property_type(schema: &Value, name: &str) -> String {
    let property = &schema["properties"][name];
    property["type"]
        .as_str()
        .or_else(|| property["format"].as_str())
        .or_else(|| property["$ref"].as_str())
        .unwrap_or("value")
        .to_owned()
}

fn output_summary(tool: &Value) -> String {
    if let Some(returns) = tool["meta"]["returns"].as_str() {
        return returns.to_owned();
    }
    schema_output_summary(&tool["output_schema"])
}

fn schema_output_summary(schema: &Value) -> String {
    if schema.is_null() {
        return "unspecified".to_owned();
    }
    if let Some(properties) = schema["properties"].as_object() {
        let fields = properties
            .keys()
            .take(6)
            .map(|name| format!("{name}: {}", schema_property_type(schema, name)))
            .collect::<Vec<_>>();
        if !fields.is_empty() {
            return fields.join(", ");
        }
    }
    schema["type"]
        .as_str()
        .or_else(|| schema["$ref"].as_str())
        .unwrap_or("structured JSON")
        .to_owned()
}

fn cli_usage(tool: &Value) -> Option<String> {
    tool["cli_usage"]
        .as_str()
        .map(|usage| usage.strip_prefix("example ").unwrap_or(usage).to_owned())
}

fn cli_flags_summary(tool: &Value) -> Option<String> {
    let flags = tool["cli_flags"].as_array()?;
    let rendered = flags
        .iter()
        .filter_map(|flag| {
            let name = flag["name"].as_str()?;
            let value_name = flag["value_name"]
                .as_str()
                .map(|value| format!(" {value}"))
                .unwrap_or_default();
            let required = if flag["required"].as_bool().unwrap_or(false) {
                " required"
            } else {
                " optional"
            };
            Some(format!("`{name}{value_name}`{required}"))
        })
        .collect::<Vec<_>>();
    (!rendered.is_empty()).then(|| rendered.join(", "))
}

fn scaffold_fallback_summary(tool: &Value) -> Option<String> {
    let fallback = &tool["meta"]["scaffold_fallback"];
    if fallback.is_null() {
        return None;
    }
    let skill = fallback["recommended_skill"].as_str()?;
    let instructions = fallback["instructions"].as_str().unwrap_or("");
    Some(format!(
        "- Elicitation fallback: recommended_skill: `{skill}`. {instructions}\n"
    ))
}

fn env_summary(tool: &Value) -> Option<String> {
    let env = tool["env"].as_array()?;
    let entries = env
        .iter()
        .filter_map(|item| {
            let name = item["name"].as_str()?;
            let mut qualifiers = Vec::new();
            if item["required"].as_bool().unwrap_or(false) {
                qualifiers.push("required");
            }
            if item["sensitive"].as_bool().unwrap_or(false) {
                qualifiers.push("sensitive");
            }
            if qualifiers.is_empty() {
                Some(format!("`{name}`"))
            } else {
                Some(format!("`{name}` ({})", qualifiers.join(", ")))
            }
        })
        .collect::<Vec<_>>();
    (!entries.is_empty()).then(|| entries.join(", "))
}

fn examples_summary(tool: &Value) -> Option<String> {
    let examples = tool["examples"].as_array()?;
    let rendered = examples
        .iter()
        .take(2)
        .map(|example| {
            let name = example["name"].as_str().unwrap_or("example");
            if let Some(args) = example["args"].as_object() {
                let args = args
                    .keys()
                    .map(|key| format!("`{key}`"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("`{name}` args: {args}")
            } else {
                format!("`{name}`")
            }
        })
        .collect::<Vec<_>>();
    (!rendered.is_empty()).then(|| rendered.join("; "))
}

fn render_primitive_section(out: &mut String, title: &str, items: &Value) {
    let Some(items) = items.as_array() else {
        return;
    };
    if items.is_empty() {
        return;
    }
    out.push_str(&format!("## {title}\n\n"));
    for item in items {
        let name = item["name"].as_str().unwrap_or("");
        let description = item["description"].as_str().unwrap_or("");
        out.push_str(&format!("- `{name}`: {description}\n"));
        if let Some(uri) = item["uri_template"].as_str() {
            out.push_str(&format!("  - URI template: `{uri}`\n"));
        }
    }
    out.push('\n');
}

fn yes_no(value: bool) -> &'static str {
    if value {
        "yes"
    } else {
        "no"
    }
}
