use super::*;
use std::sync::{Mutex, OnceLock};

static ENV_LOCK: OnceLock<Mutex<()>> = OnceLock::new();

#[test]
fn mixed_drop_in_providers_populate_generated_distribution_surfaces() {
    let _guard = ENV_LOCK.get_or_init(|| Mutex::new(())).lock().unwrap();
    let temp = tempfile::tempdir().expect("tempdir");
    let providers = temp.path().join("providers");
    fs::create_dir(&providers).expect("providers dir");
    fs::write(
        providers.join("weather.tool.ts"),
        format!(
            "export default {};\nexport async function call(input) {{ return {{ ok: true, action: input.action }}; }}\n",
            provider_manifest("weather-ts", "ai-sdk", "weather_ts")
        ),
    )
    .expect("ts provider");
    fs::write(
        providers.join("image.wasm"),
        wasm_provider(provider_manifest("image-wasm", "wasm", "image_wasm").as_bytes()),
    )
    .expect("wasm provider");
    fs::write(
        providers.join("notes.mcp.json"),
        provider_manifest("notes-mcp", "mcp", "notes_search"),
    )
    .expect("mcp provider");
    fs::write(
        providers.join("github.openapi.json"),
        provider_manifest("github-openapi", "openapi", "github_issue"),
    )
    .expect("openapi provider");

    std::env::set_var("RTEMPLATE_PROVIDER_DIR", &providers);
    let snapshot = render_provider_snapshot().expect("snapshot");
    std::env::remove_var("RTEMPLATE_PROVIDER_DIR");
    let plugin = render_distribution_plugin(&snapshot);

    for action in ["weather_ts", "image_wasm", "notes_search", "github_issue"] {
        assert!(
            contains_string(&snapshot["surfaces"]["mcp_actions"], action),
            "MCP actions should include {action}"
        );
        assert!(
            contains_string(&snapshot["surfaces"]["cli_actions"], action),
            "CLI actions should include {action}"
        );
    }
    assert!(contains_string(
        &snapshot["surfaces"]["cli_commands"],
        "ship-weather-ts"
    ));
    assert!(contains_string(
        &snapshot["surfaces"]["cli_commands"],
        "ship-alias-weather_ts"
    ));
    assert!(contains_string(
        &snapshot["surfaces"]["rest_routes"],
        "POST /v1/providers/weather-ts"
    ));
    assert!(contains_string(
        &plugin["provider_files"],
        "providers/weather.tool.ts"
    ));
    assert!(contains_string(
        &plugin["provider_files"],
        "providers/github.openapi.json"
    ));
    assert!(contains_string(
        &snapshot["surfaces"]["generated_skills"],
        "docs/generated/skills/weather-ts/SKILL.md"
    ));
    let skill = render_provider_skill(
        snapshot["providers"]
            .as_array()
            .unwrap()
            .iter()
            .find(|provider| provider["name"] == "weather-ts")
            .unwrap(),
    )
    .expect("skill");
    assert!(skill.contains("name: weather-ts"));
    assert!(skill.contains("When To Use"));
    assert!(skill.contains("weather_ts"));
    assert!(skill.contains("ship-weather-ts"));
    assert!(skill.contains("POST /v1/providers/weather-ts"));
    assert!(skill.contains("MCP"));
    assert!(skill.contains("CLI"));
    assert!(skill.contains("REST"));
    assert!(skill.contains("## Action Reference"));
    assert!(skill.contains("Required args"));
    assert!(skill.contains("Output"));

    let static_skill = render_provider_skill(
        snapshot["providers"]
            .as_array()
            .unwrap()
            .iter()
            .find(|provider| provider["name"] == "static-rust")
            .unwrap(),
    )
    .expect("static skill");
    assert!(static_skill.contains("| `elicit_name` | yes | no | no | `N/A` | `N/A` |"));
    assert!(static_skill.contains("- CLI: `N/A` - do not call this action from CLI."));
    assert!(static_skill.contains("- REST: `N/A` - do not invent an HTTP route."));
    assert!(static_skill.contains("Generated by `cargo xtask generate-provider-surfaces`"));
    assert!(static_skill.contains("rmcp-template built-in Rust actions"));
    assert!(static_skill.contains("MCP elicitation"));
    assert!(static_skill.contains("- CLI: `rtemplate echo --message MSG`"));
    assert!(static_skill.contains("- CLI flags: `--message MSG` required"));
    assert!(static_skill.contains("- Output: `EchoResult`"));
    assert!(static_skill.contains("- Output: `ScaffoldIntentReport`"));
    assert!(static_skill.contains("recommended_skill: `scaffold-project`"));
    assert!(static_skill.contains("Do not mutate files until the user approves the plan."));
}

fn provider_manifest(name: &str, kind: &str, action: &str) -> String {
    json!({
        "schema_version": 1,
        "provider": {
            "name": name,
            "kind": kind,
            "enabled": true,
            "description": format!("Generated test provider {name}.")
        },
        "tools": [{
            "name": action,
            "description": format!("Generated test action {action}."),
            "input_schema": {
                "type": "object",
                "additionalProperties": false,
                "properties": {}
            },
            "cli": {
                "enabled": true,
                "command": format!("ship-{name}"),
                "aliases": [format!("ship-alias-{action}")]
            },
            "rest": {
                "enabled": true,
                "method": "POST",
                "path": format!("/v1/providers/{name}")
            }
        }]
    })
    .to_string()
}

fn wasm_provider(manifest: &[u8]) -> Vec<u8> {
    let mut bytes = vec![0, b'a', b's', b'm', 1, 0, 0, 0];
    let name = b"rtemplate.provider";
    let mut payload = Vec::new();
    write_leb(name.len() as u32, &mut payload);
    payload.extend_from_slice(name);
    payload.extend_from_slice(manifest);
    bytes.push(0);
    write_leb(payload.len() as u32, &mut bytes);
    bytes.extend(payload);
    bytes
}

fn write_leb(mut value: u32, bytes: &mut Vec<u8>) {
    loop {
        let mut byte = (value & 0x7f) as u8;
        value >>= 7;
        if value != 0 {
            byte |= 0x80;
        }
        bytes.push(byte);
        if value == 0 {
            break;
        }
    }
}

fn contains_string(value: &Value, needle: &str) -> bool {
    value
        .as_array()
        .into_iter()
        .flatten()
        .any(|value| value.as_str() == Some(needle))
}
