openapi: 3.1.0
info:
  title: Hello Provider Example
  version: 0.1.0
paths:
  /hello:
    post:
      operationId: hello_openapi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
              additionalProperties: false
      responses:
        "200":
          description: Example response
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
